plugins {
    id 'net.neoforged.moddev' version '1.0.+'
    id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

repositories {}

dependencies {
    annotationProcessor "org.spongepowered:mixin:0.8.5"
}

sourceSets {
    main {
        java {
            srcDirs = ['../src/main/java']
        }
        resources {
            srcDirs = ['../src/main/resources']
            exclude 'fabric.mod.json'
        }
    }
}

neoForge {
    version = project.neoforge_version

    runs {
        client {
            client()
        }
        server {
            server()
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 25
}

java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

jar {
    archiveBaseName = "legacy-end-rings-neoforge"
}

publishing {
    publications {
        create("mavenJava", MavenPublication) {
            from components.java
        }
    }
}